# Arquivo de configuração do kind para ser compatível com o Ingress
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    # mapeia as portas 80 (HTTP) e 443 (HTTPS) do cluster para as do host
    extraPortMappings: 
      - containerPort: 80 
        hostPort: 80
        protocol: TCP
      - containerPort: 443
        hostPort: 443
        protocol: TCP

