# Secret do banco de dados
# Armazena informações sensíveis, como usuário e senha do db e o nome do banco
# TODO: analisar se é necessário a utilização do POSTGRES_DB
apiVersion: v1
kind: Secret
metadata:
  name: secret-database
  namespace: database
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=       # usuário do banco de dados (postgres)
  POSTGRES_PASSWORD: cG9zdGdyZXM=   # senha do banco de dados (postgres)
  POSTGRES_DB: bWVuc2FnZW5zZGI=     # nome do banco de dados (mensagensdb)
  DB_USER: cG9zdGdyZXM=
  DB_PASSWORD: cG9zdGdyZXM=
